---
abstract: 'module to convert a HPGL file into a Cadsoft Eagle script'
author:
  - 'Lieven Hollevoet <hollie@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-HPGL2Cadsoft
requires:
  Carp: 0
  Getopt::Long: 0
  Grid::Coord: 0
  IO::File: 0
  Modern::Perl: 0
  Moose: 0
  Pod::Usage: 0
  namespace::autoclean: 0
  strict: 0
resources:
  bugtracker: https://github.com/hollie/app-hpgl2cadsoft-perl/issues
  repository: git://github.com/hollie/app-hpgl2cadsoft-perl.git
version: 0.01
