# This is a basic workflow to help you get started with Actions

name: CI on master

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the releases branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
      - run: cpanm install Dist::Zilla
      - run: dzil authordeps --missing | cpanm
      - run: dzil listdeps | cpanm
      - run: RELEASE_TESTING=1 dzil prove
