name: Node Continuous Integration

on:
  pull_request:
    branches: [ master ]


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
      - run: cpanm install Dist::Zilla
      - run: dzil authordeps --missing | cpanm
      - run: dzil listdeps | cpanm
      - run: prove -lrv t

